# Generated by Django 5.2.8 on 2025-11-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usuario', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_tema', models.CharField(choices=[('claro', 'Claro'), ('obscuro', 'Obscuro')], default='claro', max_length=10)),
                ('tipo_fond', models.CharField(choices=[('color', 'Color'), ('imagen', 'Imagen')], default='color', max_length=10)),
                ('fuente', models.CharField(default='Arial', max_length=200)),
                ('tam_fuente', models.CharField(default='16px', max_length=10)),
                ('color_fuente', models.CharField(default='#000000', max_length=45)),
                ('color_primario', models.CharField(default='#3498db', max_length=20)),
                ('color_secundario', models.CharField(default='#2ecc71', max_length=45)),
                ('acentos', models.CharField(default='#e74c3c', max_length=45)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='cuenta_usr.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='cuenta_usr.usuario'),
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='cuenta_usr.perfil')),
                ('perfil_seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siguiendo', to='cuenta_usr.perfil')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('perfil_seguidor', models.F('perfil_seguido')), _negated=True), name='no_self_follow')],
                'unique_together': {('perfil_seguidor', 'perfil_seguido')},
            },
        ),
    ]
