# Generated by Django 5.2.8 on 2025-11-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_usr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='seguidores',
            options={'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='cuenta_usr_perfil',
        ),
        migrations.AlterModelTable(
            name='seguidores',
            table='cuenta_usr_seguidores',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='cuenta_usr_usuario',
        ),
    ]
