# Generated by Django 5.2.7 on 2025-11-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_usr', '0002_alter_perfil_options_alter_seguidores_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionesusuario',
            options={'verbose_name': 'ConfiguracionesUsuario', 'verbose_name_plural': 'ConfiguracionesUsuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('nombre', 'apellido_p', 'apellido_m')},
        ),
        migrations.AlterModelTable(
            name='configuracionesusuario',
            table='cuenta_usr_configuracionesusuario',
        ),
    ]
